batch-size: 128
bn-type: 2
data-set: dgraphfin
device: 0
diversity-type: cos
epochs: 10
fraud-th: 88
hidden-dim: 64
hidden-drop: 0.0
input-drop: 0.0
lr: 0.001
mlp-drop: 0.4
mlp12-dim: 128
mlp3-dim: 128
model: backbone
normal-th: 7
num-layers: 1
optim: adam
shuffle-train: true
store-model: true
to-homo: false
topk-mode: 4
train-iterations: 128
train-procedure: CT
trainable-consis-weight: 1.5
trainable-detach-mask: false
trainable-detach-y: true
trainable-div-eps: true
trainable-drop-rate: 0.2
trainable-eps: 1.0e-12
trainable-lr: 0.005
trainable-model: mlp
trainable-optim: adam
trainable-temp: 0.0001
trainable-warm-up: -1
trainable-weight-decay: 1.0e-05
training-ratio: 10
unlabel-ratio: 4
weight-decay: 1.0e-05
